### ISSUE TITLE
mongo-to-rabbit update pkg

### ISSUE THREAD

**Issue by nettashviro** [Shahar-Y/mongo-to-rabbit#18]
ADDED

support in multiple queues and middlewares
only one connection to collection
multiple msgs for a queue
when updating return the full-document
added rabbit status function
add an option to increase the number of retries reconnect to rabbit
add mongo reconnection and mongo status

**Comment by Shahar-Y** [comment]
It seems it can be closed with #17 .  Correct? @nettashviro
